# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-15 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('date', models.DateField(verbose_name='day date')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time_start', models.TimeField(verbose_name='lesson start time')),
                ('time_end', models.TimeField(verbose_name='lesson end time')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheds.Day')),
            ],
        ),
    ]
