# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-15 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheds', '0002_auto_20161015_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='week_even',
        ),
        migrations.RemoveField(
            model_name='day',
            name='week_odd',
        ),
        migrations.AddField(
            model_name='lesson',
            name='week_even',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='week_odd',
            field=models.BooleanField(default=True),
        ),
    ]
