# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-15 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheds', '0004_auto_20161016_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='name',
        ),
        migrations.AddField(
            model_name='day',
            name='weekday',
            field=models.IntegerField(default=-1, verbose_name='weekday number'),
        ),
    ]
